-- Routine Review Mode: persistence for Evening Reflection/Gratitude prompt
-- answers, so they can be shown and edited when the user reviews an
-- earlier completed step via ProgressIndicator instead of being lost on
-- every remount (journal persistence for these two screens was
-- explicitly deferred at F4 - see Reflection.jsx/Gratitude.jsx's own doc
-- comments).
--
-- Neither existing table fits this shape:
--   - journal_entries is a freeform title/body log with no date/step/
--     prompt scoping at all - a different feature (the standalone
--     Journal page), not routine-step answers.
--   - user_intentions is a single row per user with no date column -
--     "today's active intention", not a per-day history.
--
-- session_id/step_id are constrained to the ids the Session Registry
-- (src/session/sessionConstants.js, sessionDefinitions.js) and the two
-- real response-bearing pages actually use today - not an open-ended
-- free-text column - so a typo or a future unrelated feature can never
-- silently land rows in this table under an id nothing reads.
--
-- prompt_id values (stable, internal, never the displayed question
-- wording - confirmed against the exact ids Reflection.jsx/Gratitude.jsx
-- already use for their local PromptStepper state):
--   reflection: 'went-well' | 'challenged' | 'release'
--   gratitude:  'appreciated-moment' | 'who-made-better' | 'grateful-now'
--
-- local_date is the caller's own WakeWise local-calendar-day (the exact
-- `dateKey` getZonedParts(effectiveTimezone, now()) already produces for
-- Home.jsx's own MORNING_DONE_KEY/EVENING_DONE_KEY date-scoping) - never
-- computed independently in SQL and never a UTC date truncation, so a
-- user's "today" always matches what the rest of the app already calls
-- today for them, including a stale/pinned prior-day routine being
-- reviewed (routineProgress.js's own pinned dateKey is passed through
-- unchanged, never replaced with the real current day).

CREATE TABLE IF NOT EXISTS public.routine_responses (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id   text NOT NULL,
  step_id      text NOT NULL,
  prompt_id    text NOT NULL,
  local_date   date NOT NULL,
  response     text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at   timestamptz NOT NULL DEFAULT timezone('utc'::text, now())
);

-- ============================================================================
-- Validation
-- ============================================================================

ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_session_id_check
  CHECK (session_id IN ('morning-routine', 'evening-wind-down'));

ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_step_id_check
  CHECK (step_id IN ('reflection', 'gratitude'));

-- Conservative stable-id format: lowercase letters/digits, hyphen-
-- separated, must start with a letter - matches every id listed above
-- and rejects anything that looks like raw prompt wording (spaces,
-- punctuation, capitals) by construction.
ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_prompt_id_format_check
  CHECK (prompt_id ~ '^[a-z][a-z0-9]*(-[a-z0-9]+)*$');

-- Never an empty/whitespace-only row - the application layer deletes a
-- cleared response instead of saving blank text (see the clear-response
-- behaviour note below); this is the DB-level backstop for that rule.
ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_response_not_blank_check
  CHECK (length(btrim(response)) > 0);

-- 5,000 characters - no existing product limit on these two screens
-- (PromptStepper's <textarea> is unbounded today), chosen as a generous
-- but real ceiling consistent with a multi-sentence journal-style answer.
ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_response_max_length_check
  CHECK (char_length(response) <= 5000);

-- Never store markup - rejects anything containing what looks like an
-- opening/closing tag, a comment, or a doctype. Defense in depth: the
-- client also never renders this value as HTML (always plain text in a
-- <textarea>/text node, never dangerouslySetInnerHTML).
ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_response_no_html_check
  CHECK (response !~ '<[a-zA-Z/!?]');

-- ============================================================================
-- Idempotency - the exact conflict target every upsert uses. Editing an
-- existing response updates this same row; it can never create a second
-- row for the same user/session/step/prompt/date.
-- ============================================================================

ALTER TABLE public.routine_responses
  ADD CONSTRAINT routine_responses_owner_key
  UNIQUE (user_id, session_id, step_id, prompt_id, local_date);

-- Loading the complete response set for one routine visit (all
-- steps/prompts for a given user+session+date) filters directly on
-- local_date without constraining step_id/prompt_id first - the unique
-- constraint's own index (ordered user_id, session_id, step_id,
-- prompt_id, local_date) cannot serve that access pattern efficiently
-- since local_date sits behind two columns the query doesn't filter on.
-- Not redundant with it for that reason.
CREATE INDEX IF NOT EXISTS routine_responses_user_session_date_idx
  ON public.routine_responses (user_id, session_id, local_date);

-- ============================================================================
-- updated_at - no generic/reusable trigger function exists anywhere in
-- this repo today (every other updated_at column here is set by an
-- explicit `SET updated_at = now()` inside a server-side RPC - see
-- checkout_attempts' own functions). This table is written directly by
-- the client via upsert, with no RPC in front of it, so a scoped trigger
-- is the only way to guarantee updated_at is always correct regardless
-- of what the client sends - deliberately named for this table only,
-- not a shared/generic utility.
-- ============================================================================

CREATE OR REPLACE FUNCTION public.set_routine_responses_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS routine_responses_set_updated_at ON public.routine_responses;
CREATE TRIGGER routine_responses_set_updated_at
  BEFORE UPDATE ON public.routine_responses
  FOR EACH ROW
  EXECUTE FUNCTION public.set_routine_responses_updated_at();

-- ============================================================================
-- RLS - owner-only, TO authenticated only, matching journal_entries/
-- user_intentions exactly (Stage 2B migration, 20260804082844). A
-- Supabase anonymous session still authenticates as the `authenticated`
-- Postgres role (same caveat already documented on those two tables), so
-- guest write-prevention is additionally enforced client-side (guests
-- never reach the save call at all - see ActiveIntentionCard.jsx's own
-- isGuest gate for the established pattern this follows).
-- ============================================================================

ALTER TABLE public.routine_responses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "routine_responses_select_own" ON public.routine_responses;
CREATE POLICY "routine_responses_select_own" ON public.routine_responses
  FOR SELECT
  TO authenticated
  USING ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "routine_responses_insert_own" ON public.routine_responses;
CREATE POLICY "routine_responses_insert_own" ON public.routine_responses
  FOR INSERT
  TO authenticated
  WITH CHECK ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "routine_responses_update_own" ON public.routine_responses;
CREATE POLICY "routine_responses_update_own" ON public.routine_responses
  FOR UPDATE
  TO authenticated
  USING ((select auth.uid()) = user_id)
  WITH CHECK ((select auth.uid()) = user_id);

DROP POLICY IF EXISTS "routine_responses_delete_own" ON public.routine_responses;
CREATE POLICY "routine_responses_delete_own" ON public.routine_responses
  FOR DELETE
  TO authenticated
  USING ((select auth.uid()) = user_id);

-- Explicit confirmation that anon has no access at all, in addition to
-- RLS having zero anon-targeted policies (belt and suspenders, same
-- style already used for public.is_admin()'s own REVOKE/GRANT pair).
REVOKE ALL ON public.routine_responses FROM PUBLIC;
REVOKE ALL ON public.routine_responses FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.routine_responses TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.routine_responses_id_seq TO authenticated;

REVOKE ALL ON FUNCTION public.set_routine_responses_updated_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_routine_responses_updated_at() FROM anon;
